### ISSUE TITLE
Outdated manual for the new version of Bootstrap

### ISSUE THREAD

**Issue by keplerbr** [zendframework/zf2-documentation#1287]
The skeleton using the bootstrap version 3.0, while the manual uses as the version 2.X 
This confuses many beginners, <a href="http://framework.zend.com/manual/2.3/en/user-guide/forms-and-actions.html">like here (see the user comment AfC)</a>

**Comment by adamlundrigan** [comment]
None of the code in the referenced page uses Bootstrap 2, but the screenshots are likely based on the old ZendSkeletonApplication, which did.  I don't see this as an issue, though, as the intent of the page is how to build woring ZF2 forms and not how to use Bootstrap to style them.

I'll take a look at adding a notice above the Discus box advising people to use StackOverflow/IRC for questions and the issue tracker for bugs.  The latter is a bit tricky as there's now a large number of issue trackers instead of just one.
